grote/Transportr

res/menu/location_actions.xml, src/de/grobox/liberario/ui/LegPopupMenu.java, src/de/grobox/liberario/ui/StationPopupMenu.java
=> Add New Search "From Here" and "To Here" to Location Popup Menu #124

res/values/strings.xml
=> fix spelling of Hanover

res/drawable/network_francesoutheast_logo.xml, res/values/strings.xml, src/de/grobox/liberario/NetworkProviderFactory.java, src/de/grobox/liberario/TransportNetworks.java
I mainly tested the south-east region in the surroundings of Grenoble (TAG network). Has worked like a charm for 2 days straight :-)
Support for Lyon (2nd biggest french city) is lacking from Navitia, however.
=> Add support for Navitia fr-se region (south-east of France)

res/values/strings.xml
Fixing #286,
Fixed wrong year (next week it should be changed again lol)
=> Set name of places in English (1/2)

res/values/strings.xml
=> English names for transport network descriptions

src/de/grobox/liberario/activities/MainActivity.java
Fixes #282 
If you think, this is not intuitive just close this PR :wink:
=> Open "Pick a network" view when tabbing on the current network

pre-build.sh, res/values/strings.xml, src/de/grobox/liberario/NetworkProviderFactory.java, src/de/grobox/liberario/TransportNetworks.java
* removed MET according to changes in schildbach/public-transport-enabler@dee663ea54d818b2d58d22cf4d16c54746e4aa5b
* adapted pre-build.sh to these changes
=> update PTE (fixes NPE in AbstractNavitiaProvider)

res/values/strings.xml, src/de/grobox/liberario/activities/MainActivity.java, src/de/grobox/liberario/fragments/SettingsFragment.java, src/de/grobox/liberario/utils/TransportrUtils.java
In relevance to #71 
This adds a "Get Me Home"-shortcut for Android 7.1 Launcher.
=> add quickhome shortcut for Android 7.1

res/values/strings.xml, src/de/grobox/liberario/fragments/RecentTripsFragment.java
I don't do much Android development yet and I haven't built the project, but I think this is more or less what has to change to allow plurals, as suggested by TheLastProject on Transifex a year ago.
=> [UNTESTED] Pluralize message

src/de/grobox/liberario/NetworkProviderFactory.java, src/de/grobox/liberario/TransportNetworks.java
* various fixes in AbstractProviders
* changes in API_BASE for VGN, DING, HSL, TLEM
* remove the dead provider in Transportr
* remove the "secret" for VGN as this is not needed anymore due to the PTE-update
This is cherry-picked from #317.
=> update pte (v1)

src/de/grobox/liberario/activities/TripDetailActivity.java, src/de/grobox/liberario/adapters/TripAdapter.java
fixes #316 
This adds an additional check in order to not call equals on a null reference.
If the PR is OK I will also cherry-pick this to master.
=> check if numChanges is null and handle this case

app/src/main/java/de/grobox/transportr/networks/NetworkProviderFactory.java
=> Use correct language for 9292 provider

app/src/main/res/values/strings.xml
Signed-off-by: Tod Fitch <Tod@FitchDesign.com>
=> Improve np_desc_california text string.

app/src/main/res/xml/changelog_master.xml
I forgot to add the changelog in #481. I added it and the Hungary provider from #451.
=> Updated changelog

app/src/main/res/layout/location_item.xml
=> Make location item layout multi-line compatible

.clabot, app/src/main/java/de/grobox/transportr/trips/search/TripsFragment.java, app/src/main/res/layout/fragment_trips.xml
See https://github.com/grote/Transportr/issues/513 - this PR makes exception text selectable in the error screen.
=> Improve Directions Error UI

app/src/main/AndroidManifest.xml, app/src/main/res/xml/network_security_config.xml
Should hopefully resolve errors such as:
```
java.net.UnknownServiceException: CLEARTEXT communication to fahrplan.oebb.at not permitted by network security policy
okhttp3.internal.connection.RealConnection.connect(RealConnection.java:147)
okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
```
#
```
java.net.UnknownServiceException: CLEARTEXT communication to mobilapps.rejseplanen.dk not permitted by network security policy
okhttp3.internal.connection.RealConnection.connect(RealConnection.java:147)
okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAlloca …
```
=> Network Security Configuration

app/build.gradle, app/src/main/java/de/grobox/transportr/networks/TransportNetworks.kt, app/src/main/res/drawable/network_portugal_logo.xml, app/src/main/res/values/strings.xml, app/witness.gradle, artwork/networks/network_portugal_logo.svg
I added lisbon.
If there is any problem. I am happy to adapt the PR.
If this PR got accepted, when will be the next rebuild on F-Droid?
=> Add Lisbon

app/src/main/java/de/grobox/transportr/map/BaseMapFragment.kt, app/src/main/res/values-night/themes.xml, app/src/main/res/values-v21/themes.xml, app/src/main/res/values/themes.xml
Fixes #685 and #686 in two separate commits.
=> Fix theming issues

app/witness.gradle, update-dependency-pinning.sh
=> Remove linux dependency from witness.gradle

.github/PULL_REQUEST_TEMPLATE/release.md
... as documentation for the release process.
=> Add template for releases

app/src/main/java/de/grobox/transportr/trips/search/DirectionsFragment.kt, app/src/main/res/layout/fragment_directions_form.xml
A very small followup to https://github.com/grote/Transportr/pull/716#issuecomment-708349476.
=> Display 'now' in lower case letters in directions form

app/src/main/java/de/grobox/transportr/locations/LocationView.kt, app/src/main/java/de/grobox/transportr/trips/search/DirectionsFragment.kt, app/src/main/java/de/grobox/transportr/trips/search/DirectionsViewModel.kt
Fixes the bug described in https://github.com/grote/Transportr/issues/706#issuecomment-719488100.
=> Fix double swap locations bug

app/src/main/java/de/grobox/transportr/trips/search/DirectionsFragment.kt
=> Bugfix: remove correct observer

app/build.gradle, app/src/main/java/de/grobox/transportr/trips/search/DirectionsFragment.kt, app/src/main/java/de/grobox/transportr/trips/search/DirectionsViewModel.kt, app/src/main/res/layout/fragment_directions_form.xml, app/witness.gradle
=> Hide via button if current network provider does not support it

app/src/main/java/de/grobox/transportr/settings/SettingsManager.kt, app/src/main/java/de/grobox/transportr/trips/search/DirectionsViewModel.kt
=> Remember preferred means of transport
