grote/Transportr

- res/values/strings.xml
I think this one has slipped when I was sorting the strings. There's not much sense in translating `RTA` (from Chicago-Provider).
> RTA should not be translatable

- src/de/grobox/liberario/data/RecentsDB.java
In #251 an error occured due to a Location of Type `ANY` entering the database through a malformed intent. This patch prevents this from happening. (I tested that these malformed locations did not appear in the favorites.)
Closes #251.
> prevent locations of type ANY to enter the favorites

- res/values/strings.xml
I updated the description and removed Spain form it, as the renfe data available only works in Basque Country
> Update description Spain

- res/values/strings.xml
Idea: change "Trains in Switzerland" to "Switzerland", as the SBB data contains basically all public transport info for Switzerland. The OEBB data is also described as Austria (not "Trains in Austria") because there is more information available.
> Update SBB info

- res/layout/leg_details.xml
I don't know if this is the best way to fix this, but it seems to work without breaking anything.
Before:
After:
> Use all available width for leg message

- .travis.yml
I noticed that travis sometimes fails with a killed process.
I found some hints that this might not be the case when `sudo:true` is set. As far as I could test it (I started the build during different daytimes) this seems to solve the sporadic failures.
Moreover I enabled caching of dependencies and build for both `oraclejdk7`, `oraclejdk8` and `openjdk7`.
Those last two are just optional, I can also remove them.
The downturn of `sudo:true` is that it takes a bit longer to start up the machine.
> Try to fix failing Travis builds

- src/de/grobox/liberario/fragments/NearbyStationsFragment.java
fixes #314
This uses the fix by @RunasSudo to show the results of a GPS-based
search in NearbyStationsFragment.
I messed a bit around with changing orientation, restarting the app, changing fragments and could not see any degradation.
> fix NearbyStationsFragment when using GPS

- res/values/strings.xml
Some new datasets have been added to navitia: https://groups.google.com/forum/#!topic/navitia/W_74FRk57x8
Added this information (Navarra & Palma) and cleaned up the description. Removed unnecessary duplicates in description (Moveuskadi contains Renfe & Lurraldebus in Basque Country).
> Add new information in strings.xml about new GTFS data in Navitia

- app/src/main/res/values/strings.xml
With the new support for some Ontario public transit agencies added recently in Navitia, [0] Transportr already supports these locations.
[0] https://groups.google.com/forum/#!topic/navitia/hByDZkChCjc/discussion
> Update Ontario strings

- app/src/main/java/de/grobox/transportr/ui/LineView.kt
Currently, all `drawables` of the same product type e.g. in the departures list share the same common state, so when there are different foreground colors, scrolling through the list results in some ugly product icon color changing.
See these screenshots below: The first and second screenshot from the left show the same list, just scrolled a little bit. Note that on the left all bus icons are white (including the `1` one, which should be black), whereas in the middle all bus icons changed to black color.
This PR fixes this bug, the screenshot on the right was taken after the code change.
See [here](https://developer.android.com/reference/android/graphics/drawable/Drawable.html#mutate()) for more information.
> Bugfix: Prevent Product icon color blinking

- app/src/main/java/de/grobox/transportr/networks/TransportNetworks.kt
- app/src/main/res/drawable/network_hungary_logo.xml
- app/src/main/res/values/strings.xml
- artwork/networks/network_hungary_logo.svg
Hi @grote 
This PR added Hungary provider, included two cities: Budapest (capital city) and Miskolc.
Related PR: https://github.com/schildbach/public-transport-enabler/pull/195
> Added Hungary provider

- app/src/main/java/de/grobox/transportr/networks/TransportNetworks.kt
- app/src/main/res/drawable/network_fi_logo.xml
- app/src/main/res/values-ca/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-el/strings.xml
- app/src/main/res/values-eo/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-eu/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values-nb/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-ta/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/main/res/values/strings.xml
- artwork/networks/network_fi_logo.svg
Now that `HslProvider` is based on the Navitia API, the data set it uses covers a few more parts of the country than just Helsinki. This changes the description and logo of the provider to reflect that.
Related issue: #493
----
~~I took the liberty of also updating the Spanish strings, because it is my native language after all :wink:~~
This is how it looks with this patch applied:
> Show that HslProvider covers many parts of Finland

- app/src/main/java/de/grobox/transportr/locations/LocationView.kt
Setting or clearing the "to" field would mirror those changes to the "from" field.
> Fix incorrect direction field update

- app/src/main/java/de/grobox/transportr/trips/search/DirectionsViewModel.java
This PR addresses #522 and solves even a greater issue: If a via location has been chosen before hiding the via location field, the via location is still used to perform the query.
Unfortunately, Android Studio reports an "Unboxing of `isExpanded.getValue()` may produce a NullPointerException" warning, the only way to avoid this is to check manually for `null` type (which should never happen btw, as `isExpanded` is instantiated when instantiating the `ViewModel`). Not sure what would be the way to go in this case.
Fixes #522
> Don't search with via location if via field is hidden

- app/src/main/java/de/grobox/transportr/trips/BaseViewHolder.kt
- app/src/main/java/de/grobox/transportr/trips/detail/LegViewHolder.kt
- app/src/main/java/de/grobox/transportr/trips/detail/StopViewHolder.kt
- app/src/main/java/de/grobox/transportr/trips/search/TripViewHolder.kt
- app/src/main/java/de/grobox/transportr/utils/DateUtils.java
This PR unifies the delay handling for `trips.search` with `trips.detail` and by doing so applies the right color to trips with "negative delay" (so public transport services ahead of their time). It also fixes the bug to not display a double minus in front of such delays.
The second commit just moves `BaseViewHolder` to the `trips` package as it is now used by both subpackages.
Fixes #575
> Fix trip delays

- app/proguard-rules.txt
This is the result of the work done and logged in #585: It just adds four lines to the Proguard rules to prevent throwing serialization methods for `Trip.path` away.
Fixes #585.
> Add proguard rule to keep path serialization

- app/src/main/java/de/grobox/transportr/trips/detail/StopViewHolder.kt
When no `arrivalTime` is set, the width of the `fromTime` TextView is changed to the width of the formatted current time, preventing aligning errors.
Fixes #587
> Align stops in TripDetailsFragment even without times

- app/src/main/java/de/grobox/transportr/trips/search/DirectionsViewModel.java
- app/src/main/java/de/grobox/transportr/trips/search/TripsFragment.java
- app/src/main/java/de/grobox/transportr/trips/search/TripsRepository.kt
- app/src/main/java/de/grobox/transportr/utils/Linkify.java
- app/src/main/res/values-ca/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-el/strings.xml
- app/src/main/res/values-eo/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-eu/strings.xml
- app/src/main/res/values-fa/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values-nb/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-sv/strings.xml
- app/src/main/res/values-uk/strings.xml
- app/src/main/res/values/strings.xml
This PR adresses #614 and #615, by implementing the idea mentioned by @TheLastProject:
> Why not just remove the instructions and add a title and body GET param to the new issue URL so it gets prefilled with the correct data? https://help.github.com/en/articles/about-automation-for-issues-and-pull-requests-with-query-parameters
I had to implement a new simplified `Linkify` method as the official one always lowercases the url. Additionally, the link to PTE is only showed if the error wasn't caused by the internet connection or a `SocketTimeout`.
The prefilled issue message looks like [this](https://github.com/schildbach/public-transport-enabler/issues/new?title=FRANCESOUTHEAST%3A%20java.lang.NullPointerException&body=%23%23%23%20Query%0A-%20NetworkId%3A%20%60FRANCESOUTHEAST%60%0A-%20From%3A …
> Better handling for reporting PTE issues

- README.md
This PR adapts the README after switching to gradle wrapper for this project as requested by @grote in https://github.com/grote/Transportr/pull/636#issuecomment-548798473.
> adapt README to use gradle wrapper

- app/src/main/java/de/grobox/transportr/departures/DeparturesActivity.java
This PR partly fixes #623 by checking if PTE returns an empty list. In this case, the error page is shown.
> Departures: Show error if returned list is empty

- app/src/main/java/de/grobox/transportr/map/BaseMapFragment.kt
- app/src/main/res/layout/fragment_map.xml
- app/src/main/res/layout/fragment_trip_map.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/themes.xml
This PR adds attribution to Mapbox and OpenStreetMap as required by the [attribution guidelines](https://docs.mapbox.com/help/how-mapbox-works/attribution/#mapbox-maps-sdk-for-android) to both map fragments in use. On smaller devices, the attribution would be wrapped into two lines.
Fixes #628.
> Add required OSM and Mapbox attribution

- app/src/main/res/layout/fragment_map.xml
- app/src/main/res/layout/fragment_trip_map.xml
As a followup to #628  and #672, this PR adds the mapbox logo as also required by the  [attribution guidelines](https://docs.mapbox.com/help/how-mapbox-works/attribution/#mapbox-maps-sdk-for-android).
Also move the text attribution more to the lower-left edge.
> Add mapbox logo to attribution

- app/src/main/res/values/strings.xml
With my request for adding Hamilton (Ontario) GTFS data to Navitia being granted [1], Transportr now automatically supports this location too. The updated strings maintain geographical order (east to west); feel free to alter this if this is inconsistent somehow.
Address search does not work for Hamilton at this point, only bus stops show up (based on my informal testing), but I understand from issue #559 that this is to be taken up with Navitia as well.
Thank you for explaining in detail how to contribute [2], it really helped a lot.
This merge request was inspired by #423.
I accept the Contributor License Agreement [3] whenever contributing to Transportr.
[1] https://groups.google.com/forum/#!topic/navitia/mK2TMKqcfjE
[2] https://transportr.app/contribute/
[3] …
> Added Hamilton and its HSR to Ontario strings

- app/src/main/java/de/grobox/transportr/utils/IntentUtils.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/de/grobox/transportr/utils/IntentUtilsTest.kt
- recognize `geo:0,0?q=lat,lon` intents as per [Android docs](https://developer.android.com/guide/components/intents-common\#ViewMap) and as used by Transportr itself
- exclude Transportr from "show on external map"
Fixes #698
> Improved geo intents

- app/src/main/java/de/grobox/transportr/networks/PickTransportNetworkActivity.kt
I am building with rather recent tools, guess that's why this bug showed up. Fixed it.
https://developer.android.com/reference/kotlin/android/app/Activity#onSaveInstanceState(android.os.Bundle,%20android.os.PersistableBundle)
> Fixed function definition to actually override onSaveInstanceState

- app/src/main/java/de/grobox/transportr/trips/detail/TripUtils.kt
- app/src/main/java/de/grobox/transportr/utils/IntentUtils.kt
handle ActivityNotFoundException instead of manually resolving calendar intent (by default not allowed on API level >= 30)
bug reproduced on Android 12 emulator, fix tested on both API 31 and 22 (Android 5.1) with and without calendar applications installed
fixes #795, fixes #818
> Fix not finding installed calendar apps

- .github/workflows/build.yml
- app/build.gradle
- app/proguard-multidex.txt
- app/src/debug/java/de/grobox/transportr/TransportrDebugApplication.kt
- app/src/main/java/de/grobox/transportr/networks/RegionViewHolder.kt
- app/src/main/java/de/grobox/transportr/ui/TransportrChangeLog.kt
- app/witness.gradle
This PR bumps minSdk to 21, and as such makes Transportr only compatible with Android devices running Android version 5.0 or above. This is done to simplify maintenance and fix bugs related to old versions.
This fixes:
- https://github.com/grote/Transportr/issues/721;
- https://github.com/grote/Transportr/issues/738;
- https://github.com/grote/Transportr/issues/471.
> Bump minSdk to 21

- .clabot
- .github/workflows/build.yml
Some older actions used node12 and this version is deprecated -> more information here https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
> Update Github actions

- app/proguard-rules.txt
following instructions from https://github.com/mikepenz/AboutLibraries/tree/v6.2.0#proguard
fixes #793
> Proguard: keep strings for about > libraries

- app/src/main/java/de/grobox/transportr/networks/TransportNetworks.kt
Reenables WienerLinien provider as it works on version 2.1.5 without any problems
> Reenable Wiener Linien provider

- app/src/main/java/de/grobox/transportr/ui/TimeDateFragment.kt
> Fix timePicker minutes always set to current time

- app/src/main/java/de/grobox/transportr/map/PositionController.kt
This is a quick fix that should close #911.
@Kelvino9 @licaon-kter could you try it out?
> Fix location provider

- app/src/main/java/de/grobox/transportr/settings/SettingsFragment.kt
- app/src/main/java/de/grobox/transportr/settings/SettingsManager.kt
- app/src/main/res/xml/preferences.xml
- fixes #913 by changing the default to "auto" (follow system)
- fixes #909 by only checking for system-wide theme if "auto" is enabled
> Fix some theming-related issues

- app/build.gradle
- app/src/main/res/xml/changelog_master.xml
- fastlane/metadata/android/en-US/changelogs/125.txt
Here are the steps to follow when preparing a new release (some custom tasks added for this release). Please check the following boxes with an `x` when done:
* ~~update PTE to the latest commit at [opentransitmap](https://gitlab.com/opentransitmap/public-transport-enabler/-/commits/master) and run `./update-dependency-pinning.sh`~~
* ~~update translations from [Transifex](https://www.transifex.com/) using `tx pull --mode=developer -a` in the root folder (you need proper permissions to do that)~~
* ~~add newly supported languages to the two arrays in [`app/src/main/res/values/arrays.xml`](https://github.com/grote/Transportr/blob/master/app/src/main/res/values/arrays.xml#L16)~~
This is just a fixup release for 2.2.0 mainly fixing #911 and raising the target API level to 33 to enable …
> Release 2.2.1

- app/build.gradle
- app/src/main/res/xml/changelog_master.xml
- fastlane/metadata/android/en-US/changelogs/127.txt
Here are the steps to follow when preparing a new release. Please check the following boxes with an x when done:
- ~~[ ] update translations from Transifex using tx pull --mode=developer -a in the root folder (you need proper permissions to do that)~~ (I'm not sure I have the permissions, and it's probably not really usefull)
- ~~[ ] add newly supported languages to the two arrays in app/src/main/res/values/arrays.xml~~
This bugfix release should fix #972. Tested the release build and its runs fine on Android 13 device.
@grote could you build the release APK and post it in the thread so everyone could test it? (and if you have time, maybe also give it a try).
> Release 2.2.3
